### ISSUE TITLE
Add manually invoiced projects

### ISSUE THREAD

**Issue by searls** [testdouble/present#100]
Every now and then we have an exceptional project which isn't invoiced by rate (say a contract fixes what we bill, as is common in training gigs) and which poses a risk if we generate a rate-calculated invoice and send it without communicating or intervening. 

This issue would add a checkbox to the project to indicate it's manually invoiced and then when an invoice is in review in Present, the total either zeroed out when sent to harvest (to be edited in harvest) or entered into Present so that present will have that invoiced total data for use in later reports

**Comment by searls** [comment]
did i just finish this and never merge it?

**Comment by tkaufman** [comment]
Same as #102 ?
