### ISSUE TITLE
Tim's Hours

### ISSUE THREAD

**Issue by tkaufman** [testdouble/present#46]
Tim somehow wound up with 2x the days in the week of 10/5 - 10/11. This caused us to double invoice him for that week

**Comment by searls** [comment]
This was fixed a bit ago I added a multi-column key constraint to prevent multiple entries for the same timesheet, day, and project. It had been caused by a race condition when two GET requests were sent to a timesheet when it was first being generated.

**Comment by searls** [comment]
Fixed by https://github.com/testdouble/present/commit/51358a9278abc31f58333fbf556c2a52c89a0b74 and the surrounding commits
