### ISSUE TITLE
Remove User

### ISSUE THREAD

**Issue by tkaufman** [testdouble/present#47]
Would be nice to be able to delete users.

**Comment by searls** [comment]
i think that we probably want to keep them around in the DB for reporting purposes, but maybe just hide them from everywhere we might find them by setting them inactive. Agree?

If so, we already have an `active` flag on the `User` model. So for example if we want to make Josh Hoff inactive, we'd just need to `User.find_by(:name => "Josh Hoff").update!(:active => false)` and then follow up by making sure he was hidden from everything other than our reports.

**Comment by searls** [comment]
This is fixed! Just uncheck "Active" from the /users/:id/edit page
