### ISSUE TITLE
Improve the Notes field

### ISSUE THREAD

**Issue by searls** [testdouble/present#61]
Now that Internal requires Notes, the field is more than just the business of one project team. I have a few ideas for making it better:

- [ ] show it every week of the project as oppposed to invoice weeks; current behavior made sense when they were literally "invoice notes", but it'd be more pleasant if the notes were stored weekly and concatenated for the sake of invoices.
- [ ] some kind of autosave or localstorage backup (writing a bunch of notes and then losing it by not pressing update would be awful
- [ ] ~~markdown support~~ some kind of standard format to make bundling notes easier for @tkaufman and/or visualizing across people

cc/@jasonkarns @davemo /whoever else we chatted about this on with slack

**Comment by davemo** [comment]
Showing it every week is good enough for me; the other things you've listed (autosave, markdown) are just nice-to-haves.

**Comment by jasonkarns** [comment]
autosave would be good. Would the markdown only be rendered as html in
report view? I don't think we really need any markdown preview given how
short most notes would be

**Comment by andrewvida** [comment]
@searls do we also want to a implement a standard for notes entry, for @tkaufman’s sake?

**Comment by danthompson** [comment]
this would be great. :+1: A format would be great, as long as it's dead simple. I've been doing the following...

```
2015-02-09: This my note fore this day
2015-02-10: This my note fore this day
...
2015-02-13: This my note fore this day
```

**Comment by searls** [comment]
@andrewvida / @jasonkarns / @danthompson -- point about markdown is well taken. I think what I was really meaning when I typed that was "a standard format for notes"

I don't know what that needs to be. Just a little style guide popup link? I don't want to enforce client-side logic into a textarea but I don't want total chaos either. Maybe style guide plus a little validation to smell/lint whether it looks formatted right?
