### ISSUE TITLE
Change from GitHub oauth

### ISSUE THREAD

**Issue by tkaufman** [testdouble/present#65]
Wondering if we should move away from github oauth. It seems to require a tighter relationship with time tracker and the test double organization than there should be.

**Comment by searls** [comment]
Now that #39 has been addressed, I don't think there are any technical blockers to this. I imagine it means we'd just need new/create actions for `UsersController`, a self-service password change (or add password to the existing UsersController edit/update actions), and some bcrypts.

We can probably skirt the other niceties like a password reset flow as long as an admin is able to go in and reset a temporary password while impersonating.

**Comment by tkaufman** [comment]
Duplicate of #111
