### ISSUE TITLE
Refactor Timesheet#billable_time_human

### ISSUE THREAD

**Issue by searls** [testdouble/present#79]
This was a one-off method I wrote for a specific alert window and has zero other uses, so it's very low churn. However, its complexity is enough for Code Climate to score it an [F](https://codeclimate.com/github/testdouble/present/Timesheet). 

Is it worth refactoring this method? If so, what's appropriate? Simply getting it out of the Timesheet class and adding indirection? Throwing it in a view helper to sweep it under a rug? Splitting it out into private methods further driving up `Timesheet`'s method count?

**Comment by kbaribeau** [comment]
Here's a link to the (now fixed) problematic version of the method:

https://github.com/testdouble/present/blob/f43757bc810b94b01510c81c1d3a28ee5d276835/app/models/timesheet.rb#L92-L96

**Comment by searls** [comment]
FWIW, CodeClimate doesn't like the any better :wink: 

![screen shot 2015-06-04 at 15 54 14](https://cloud.githubusercontent.com/assets/79303/7993127/fbed07a6-0ad1-11e5-92a4-6d9163ab002d.png)

**Comment by kbaribeau** [comment]
Interesting. I like it better. It's got more names in it than the previous version.

**Comment by searls** [comment]
Sorry kevin but code quality algorithms are always right. Can't trust humans.
