### ISSUE TITLE
Update pairing reminders to observe to next business day

### ISSUE THREAD

**Issue by searls** [testdouble/present#84]
I get all mine on sunday

**Comment by rmcastil** [comment]
@searls does it still send out the reminder if you already filled out the entry? I haven't gotten a reminder the last two cycles. But this time I filled early so I wasn't sure if that was a coincidence.

**Comment by andrewvida** [comment]
@searls Does the `send_reminder_emails` task run every day in production?

**Comment by searls** [comment]
I don't know, but probably
