### ISSUE TITLE
Present /users as a nice agents roster 

### ISSUE THREAD

**Issue by searls** [testdouble/present#94]
Since everybody on the team uses Present, it is already basically a source of record for who's a full-timer, who's a contractor, who's active/inactive, and (for the people we fail to inactivate) who's billed at all recently. That suggests it might be a good way to generate a roster of everyone currently at the company.

I'm just imagining a table of names at the moment, but might be a good place to aggregate github, twitter, email links and so forth to make it easier for folks to check on their own without needing to ask someone

cc/ @tkaufman to gauge interest. seems like it wouldn't be very time consuming to implement given how the /users resourse is already pretty CRUD-ey

**Comment by jasonkarns** [comment]
+1

/agents instead of /users?

**Comment by danthompson** [comment]
Yes! I'm greatly interested. :shaved_ice:

**Comment by searls** [comment]
@jasonkarns how about a route alias? `User` is the model and I like to keep things obvious. So far we've been pretty good about keeping Present test double meme generic, but that's not a high priority since we have I think 1 other user.

**Comment by jasonkarns** [comment]
yep, generic is good. meme is good. alias is perfect
